---
# Install docker
# 

- apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable

- apt:
    name: docker-ce=17.12.1~ce-0~ubuntu
